name: version-collector

on:
  workflow_call:
    outputs:
      package-version:
        description: 'The package version'
        value: ${{ jobs.package-version.outputs.version }}

jobs:
  package-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.pkgversion.outputs.version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: get package version
        id: pkgversion
        run: |
          export ver=$(cat package.json | jq -r .version)
          echo "Outputting version: ${ver}"
          echo "version=${ver}" >> $GITHUB_OUTPUT
